BackItems = {

    -- ORDERING
    -- Police weapons
    -- Normal weapons
    -- Items
    -- Chains     
    
    
    -- POLICE WEAPONS (HOLSTER POSITION)
        ["weapon_glock"] = {
            model="w_pi_glock", 
            back_bone = 58271,
            x = 0.0,
            y = 0.05,
            z = -0.1,
            x_rotation = -65.0,
            y_rotation = 0.0,
            z_rotation = 0.0,
        },
    -- END POLICE WEAPONS
    
    -- START WEAPONS ON BACK
        ["weapon_sledgeham"] = {
            model="w_me_sledgeham", 
            back_bone = 24818,
            x = 0.25,
            y = -0.15,
            z = 0.25,
            x_rotation = 0.0,
            y_rotation = 220.0,
            z_rotation = 0.0,
        },
        ["weapon_bats"] = {
            model="w_me_baseball_bat_metal", 
            back_bone = 24818,
            x = 0.25,
            y = -0.15,
            z = 0.25,
            x_rotation = 0.0,
            y_rotation = 220.0,
            z_rotation = 0.0,
        },
        ["weapon_grenadelauncher_smoke"] = {
            model="w_lr_potatolauncher", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_sniperrifle2"] = {
            model="w_sr_sniperrifle2", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_m14"] = {
            model="w_sr_m14", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_dragunov"] = {
            model="w_sr_dragunov", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_sniperrifle"] = {
            model="prop_gun_case_01", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 260.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_mg"] = {
            model="w_mg_mg", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_assaultrifle2"] = {
            model="w_ar_assaultrifle2", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_flamethrower"] = {
            model="w_mg_flamethrower", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_militaryrifle"] = {
            model="w_ar_militaryrifle", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_bullpuprifle_mk2"] = {
            model="w_ar_bullpuprifle_mk2", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_specialcarbine_mk2"] = {
            model="w_ar_scar", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_specialcarbine"] = {
            model="w_ar_specialcarbine", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_compactrifle"] = {
            model="w_ar_draco", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_bullpuprifle"] = {
            model="w_ar_bullpuprifle", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_advancedrifle"] = {
            model="w_ar_groza", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_carbinerifle_mk2"] = {
            model="w_ar_carbineriflemk2", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_carbinerifle"] = {
            model="w_ar_carbinerifle", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_assaultrifle_mk2"] = {
            model="w_ar_assaultriflemk2", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_assaultrifle"] = {
            model="w_ar_assaultrifle", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_machete"] = {
            model="w_me_machette_lr", 
            back_bone = 24818,
            x = 0.22,
            y = -0.15,
            z = -0.10,
            x_rotation = -175.0,
            y_rotation = 105.0,
            z_rotation = 180.0,
        },
        ["weapon_ltl"] = {
            model="w_sg_ltl", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_combatshotgun"] = {
            model="w_sg_combatshotgun", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_autoshotgun"] = {
            model="w_sg_autoshotgun", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_musket"] = {
            model="w_ar_musket", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_sawnoffshotgun"] = {
            model="w_sg_sawnoff", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_pumpshotgun_mk2"] = {
            model="w_sg_pumpshotgunmk2", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_pumpshotgun"] = {
            model="w_sg_izh81", 
            back_bone = 24818,
            x = -0.15,
            y = -0.15,
            z = -0.12,
            x_rotation = 180.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["weapon_heavyshotgun"] = {
            model="w_sg_heavyshotgun", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_bullpupshotgun"] = {
            model="w_sg_bullpupshotgun", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_assaultshotgun"] = {
            model="w_sg_assaultshotgun", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_nailgun"] = {
            model="w_sb_nailgun", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_microsmg3"] = {
            model="w_sb_microsmg3", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_microsmg2"] = {
            model="w_sb_microsmg2", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_minismg2"] = {
            model="w_sb_skorpion", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_raycarbine"] = {
            model="w_sb_raycarbine", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_gusenberg"] = {
            model="w_sb_gusenberg", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_combatpdw"] = {
            model="w_sb_mpx", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_assaultsmg"] = {
            model="w_sb_assaultsmg", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_smg_mk2"] = {
            model="w_sb_smgmk2", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_smg"] = {
            model="w_sb_mp5", 
            back_bone = 24818,
            x = -0.15,
            y = -0.15,
            z = 0.0,
            x_rotation = 10.0,
            y_rotation = -80.0,
            z_rotation = 180.0,
        },
        ["weapon_microsmg"] = {
            model="w_sb_microsmg", 
            back_bone = 24818,
            x = 0.0,
            y = -0.15,
            z = 0.10,
            x_rotation = 175.0,
            y_rotation = -175.0,
            z_rotation = 180.0,
        },
        ["weapon_rpg"] = {
            model="w_lr_rpg", 
            back_bone = 24818,
            x = 0.2,
            y = -0.17,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 180.0,
            z_rotation = 180.0,
        },
        ["weapon_firework"] = {
            model="w_lr_rpg", 
            back_bone = 24818,
            x = 0.2,
            y = -0.17,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 180.0,
            z_rotation = 180.0,
        },
        ["rpg_ammo"] = {
            model="w_lr_rpg_rocket", 
            back_bone = 24818,
            x = 0.2,
            y = -0.17,
            z = 0.1,
            x_rotation = 0.0,
            y_rotation = 180.0,
            z_rotation = -90.0,
        },
        ["firework_ammo"] = {
            model="ind_prop_firework_01", 
            back_bone = 24818,
            x = 0.2,
            y = -0.17,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 180.0,
            z_rotation = -90.0,
        },

        --CUSTOM WEAPONS
        ["weapon_ak47"] = {
            model="w_ar_ak47",
            back_bone = 24818,
            x = -0.0,
            y = -0.17,
            z = 0.08,
            x_rotation = 0.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["weapon_m70"] = {
            model="w_ar_m70",
            back_bone = 24818,
            x = -0.0,
            y = -0.17,
            z = 0.08,
            x_rotation = 0.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["weapon_remington"] = {
            model="w_sg_remington",
            back_bone = 24818,
            x = -0.0,
            y = -0.17,
            z = 0.08,
            x_rotation = 0.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["weapon_m110"] = {
            model="w_sr_m110",
            back_bone = 24818,
            x = 0.0,
            y = -0.17,
            z = -0.12,
            x_rotation = 0.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["weapon_huntingrifle"] = {
            model="w_sr_huntingrifle",
            back_bone = 24818,
            x = 0.0,
            y = -0.17,
            z = -0.12,
            x_rotation = 0.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["weapon_uzi"] = {
            model="w_sb_uzi",
            back_bone = 24818,
            x =  0.12,
            y = -0.17,
            z = -0.0,
            x_rotation = 0.0,
            y_rotation = -180.0,
            z_rotation = 0.0,
        },
        ["weapon_mp9"] = {
            model="w_sb_mp9",
            back_bone = 24818,
            x =  0.12,
            y = -0.17,
            z = -0.0,
            x_rotation = 0.0,
            y_rotation = -180.0,
            z_rotation = 0.0,
        },
        ["weapon_mk14"] = {
            model="w_sr_mk14",
            back_bone = 24818,
            x = 0.0,
            y = -0.17,
            z = -0.12,
            x_rotation = 0.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["weapon_mossberg"] = {
            model="w_sg_mossberg",
            back_bone = 24818,
            x =  0.12,
            y = -0.17,
            z = -0.0,
            x_rotation = 0.0,
            y_rotation = -180.0,
            z_rotation = 0.0,
        },
        ["weapon_m4"] = {
            model="w_ar_m4",
            back_bone = 24818,
            x = -0.0,
            y = -0.17,
            z = 0.08,
            x_rotation = 0.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["weapon_hk416"] = {
            model="w_ar_hk416",
            back_bone = 24818,
            x = -0.0,
            y = -0.17,
            z = 0.08,
            x_rotation = 0.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["weapon_scarh"] = {
            model="w_ar_scarh",
            back_bone = 24818,
            x =  0.12,
            y = -0.17,
            z = -0.0,
            x_rotation = 0.0,
            y_rotation = 180.0,
            z_rotation = 0.0,
        },
        ["weapon_mac10"] = {
            model="w_sb_mac10",
            back_bone = 24818,
            x = 0.0,
            y = -0.17,
            z = -0.12,
            x_rotation = 0.0,
            y_rotation = -180.0,
            z_rotation = 180.0,
        },
        ["weapon_katana"] = {
        model="w_me_katana",
        back_bone = 24818,
        x = -0.2,
        y = -0.15,
        z = 0.12,
        x_rotation = 0.0,
        y_rotation = -120.0,
        z_rotation = 180.0,
        },
    -- END WEAPONS ON BACK
    
    -- ITEMS ON BACK START
        ["meth"] = {
            model="hei_prop_pill_bag_01", 
            back_bone = 24818,
            x = -0.1,
            y = -0.17,
            z = 0.12,
            x_rotation = 0.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
        ["methbag"] = {
            model="bkr_prop_meth_smallbag_01a", 
            back_bone = 24818,
            x = -0.1,
            y = -0.17,
            z = 0.03,
            x_rotation = 180.0,
            y_rotation = 90.0,
            z_rotation = 90.0,
        },
        ["coke_brick"] = {
            model="bkr_prop_coke_cutblock_01", 
            back_bone = 24818,
            x = -0.20,
            y = -0.17,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 90.0,
            z_rotation = 90.0,
        },
    -- ITEMS ON BACK END

        ["qb-wingsuit"] = {
            model="np_wingsuit_open", 
            back_bone = 24818,
            x = 0.00,
            y = -0.10,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
        
        ["wingsuit_open"] = {
            model="np_wingsuit_open", 
            back_bone = 24818,
            x = 0.00,
            y = -0.10,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
        ["wingsuit_closed"] = {
            model="np_wingsuit_closed", 
            back_bone = 24818,
            x = 0.00,
            y = -0.10,
            z = 0.0,
            x_rotation = 0.0,
            y_rotation = 90.0,
            z_rotation = 0.0,
        },
    
    -- CHAINS ON NECK START
        ["cerberus_chain"] = {
            model="cerberus_chain",
            back_bone = 10706,
            x = -0.02,
            y = 0.02,
            z = -0.06,
            x_rotation = -366.0,
            y_rotation = 19.0,
            z_rotation = -163.0,
        }, 
        ["mdm_chain"] = {
            model="mdm_chain", 
            back_bone = 10706,
            x = -0.02,
            y = 0.02,
            z = -0.06,
            x_rotation = -366.0,
            y_rotation = 19.0,
            z_rotation = -163.0,
        }, 
        ["esv_chain"] = {
            model="esv_chain", 
            back_bone = 10706,
            x = -0.02,
            y = 0.02,
            z = -0.06,
            x_rotation = -366.0,
            y_rotation = 19.0,
            z_rotation = -163.0,
        }, 
        ["gsf_chain"] = {
            model="gsf_chain", 
            back_bone = 10706,
            x = -0.02,
            y = 0.02,
            z = -0.06,
            x_rotation = -366.0,
            y_rotation = 19.0,
            z_rotation = -163.0,
        }, 
    -- CHAINS ON NECK END
    -- ARM BONE
        ["medicalbag"] = {
            model="xm_prop_x17_bag_med_01a", 
            back_bone = 28422,
            x = 0.37,
            y = 0.00,
            z = -0.02,
            x_rotation = -50.0,
            y_rotation = -90.0,
            z_rotation = 0.00,
        },
          
    }
    