-- insert into: qb-core/shared/items.lua

-- Health Parts | T1GER Mechanic System
['radiator'] 			= {['name'] = 'radiator', 			['label'] = 'Radiator', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'radiator.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Health Part - Radiator'},
['fuel_pump'] 			= {['name'] = 'fuel_pump', 			['label'] = 'Fuel Pump', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'fuel_pump.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Health Part - Fuel Pump'},
['brakes']              = {['name'] = 'brakes', 			['label'] = 'Brakes', 				['weight'] = 1,		['type'] = 'item',		['image'] = 'brakes.png', 				['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Health Part - Brakes'},
['drive_shaft'] 		= {['name'] = 'drive_shaft',		['label'] = 'Drive Shaft',			['weight'] = 1,		['type'] = 'item',		['image'] = 'drive_shaft.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Health Part - Drive Shaft'},
['alternator'] 			= {['name'] = 'alternator', 		['label'] = 'Alternator', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'alternator.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Health Part - Alternator'},
['clutch']              = {['name'] = 'clutch', 			['label'] = 'Clutch', 				['weight'] = 1,		['type'] = 'item',		['image'] = 'clutch.png', 				['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Health Part - Clutch'},

-- Service Parts | T1GER Mechanic System
['oil_filter'] 			= {['name'] = 'oil_filter', 		['label'] = 'Oil + Filter', 		['weight'] = 1,		['type'] = 'item',		['image'] = 'oil_filter.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Service Part - Oil + Filter'},
['air_filter'] 			= {['name'] = 'air_filter', 		['label'] = 'Air Filter', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'air_filter.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Service Part - Air Filter'},
['fuel_filter']			= {['name'] = 'fuel_filter', 		['label'] = 'Fuel Filter', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'fuel_filter.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Service Part - Fuel Filter'},
['coolant']				= {['name'] = 'coolant',			['label'] = 'Coolant',				['weight'] = 1,		['type'] = 'item',		['image'] = 'coolant.png', 				['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Service Part - Coolant'},
['brake_fluid']			= {['name'] = 'brake_fluid',		['label'] = 'Brake Fluid', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'brake_fluid.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Service Part - Brake Fluid'},
['steering_fluid']		= {['name'] = 'steering_fluid',		['label'] = 'Power Steering Fluid',	['weight'] = 1,		['type'] = 'item',		['image'] = 'steering_fluid.png', 		['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Service Part - Power Steering Fluid'},
['transmission_fluid']	= {['name'] = 'transmission_fluid',	['label'] = 'Transmission Fluid', 	['weight'] = 1,		['type'] = 'item',		['image'] = 'transmission_fluid.png',	['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Service Part - Transmission Fluid'},
['spark_plugs']			= {['name'] = 'spark_plugs', 		['label'] = 'Spark Plugs', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'spark_plugs.png',			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Service Part - Spark Plugs'},
['drive_belt']			= {['name'] = 'drive_belt',			['label'] = 'Drive Belt',			['weight'] = 1,		['type'] = 'item',		['image'] = 'drive_belt.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Service Part - Drive Belt'},
['flywheel']			= {['name'] = 'flywheel', 			['label'] = 'Flywheel', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'flywheel.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Service Part - Flywheel'},
['tires']				= {['name'] = 'tires', 				['label'] = 'Tires', 				['weight'] = 1,		['type'] = 'item',		['image'] = 'tires.png', 				['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Service Part - Tires'},

-- Body Parts | T1GER Mechanic System
['part_door']			= {['name'] = 'part_door', 			['label'] = 'Door Part', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'part_door.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Body Part - Door'},
['part_hood']			= {['name'] = 'part_hood', 			['label'] = 'Hood Part', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'part_hood.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Body Part - Hood'},
['part_trunk']			= {['name'] = 'part_trunk', 		['label'] = 'Trunk Part', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'part_trunk.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Body Part - Trunk'},
['part_window']			= {['name'] = 'part_window',		['label'] = 'Window Part', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'part_window.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Body Part - Window'},
['part_wheel']			= {['name'] = 'part_wheel', 		['label'] = 'Wheel Part', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'part_wheel.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Body Part - Wheel'},

-- Kits | T1GER Mechanic System
['repairkit']			= {['name'] = 'repairkit', 			['label'] = 'Repair Kit', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'repairkit.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Repair Kit'},
['repairkit_adv']		= {['name'] = 'repairkit_adv', 		['label'] = 'Repair Kit Advanced',	['weight'] = 1,		['type'] = 'item',		['image'] = 'repairkit_adv.png', 		['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Repair Kit Advanced'},
['patchkit']			= {['name'] = 'patchkit', 			['label'] = 'Patch Kit', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'patchkit.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Patch Kit for health/service parts'},
['carjack']				= {['name'] = 'carjack', 			['label'] = 'Car Jack', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'carjack.png', 				['unique'] = false,		['useable'] = false,	['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Car Jack'},
['fuel_can']			= {['name'] = 'fuel_can', 			['label'] = 'Fuel Can', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'fuel_can.png', 			['unique'] = false,		['useable'] = false,	['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Fuel Can with fuel'},
['jump_starter']		= {['name'] = 'jump_starter', 		['label'] = 'Jump Starter', 		['weight'] = 1,		['type'] = 'item',		['image'] = 'jump_starter.png', 		['unique'] = false,		['useable'] = false,	['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Jump Starter for vehicle battery'},
['tire_repairkit']		= {['name'] = 'tire_repairkit', 	['label'] = 'Tire Repair Kit', 		['weight'] = 1,		['type'] = 'item',		['image'] = 'tire_repairkit.png', 		['unique'] = false,		['useable'] = false,	['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Tire Repair Kit for bursted tires'},

-- Prop Emotes | T1GER Mechanic System
['roadcone']			= {['name'] = 'roadcone', 			['label'] = 'RoadCone', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'roadcone.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Spawn a road cone prop'},
['toolstrolley']		= {['name'] = 'toolstrolley', 		['label'] = 'Tools Trolley', 		['weight'] = 1,		['type'] = 'item',		['image'] = 'toolstrolley.png', 		['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Spawn a tools trolley prop'},
['toolbox']             = {['name'] = 'toolbox', 			['label'] = 'Tool Box', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'toolbox.png', 				['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Spawn a toolbox prop'},
['enginehoist']			= {['name'] = 'enginehoist', 		['label'] = 'Engine Hoist', 		['weight'] = 1,		['type'] = 'item',		['image'] = 'enginehoist.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Spawn an engine hoist prop'},
['consign']				= {['name'] = 'consign', 			['label'] = 'Consign', 				['weight'] = 1,		['type'] = 'item',		['image'] = 'consign.png', 				['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Spawn a consign prop'},
['roadbarrier']			= {['name'] = 'roadbarrier', 		['label'] = 'Road Barrier', 		['weight'] = 1,		['type'] = 'item',		['image'] = 'roadbarrier.png', 			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Spawn a road barrier prop'},

-- Materials | T1GER Mechanic System
['scrap_metal']			= {['name'] = 'scrap_metal',		['label'] = 'Scrap Metal',          ['weight'] = 1,		['type'] = 'item',		['image'] = 'scrap_metal.png', 			['unique'] = false,		['useable'] = false,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Material - Scrap Metal'},
['steel']				= {['name'] = 'steel', 				['label'] = 'Steel', 				['weight'] = 1,		['type'] = 'item',		['image'] = 'steel.png', 				['unique'] = false,		['useable'] = false,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Material - Steel'},
['aluminium']			= {['name'] = 'aluminium', 			['label'] = 'Aluminium', 			['weight'] = 1,		['type'] = 'item',		['image'] = 'aluminium.png', 			['unique'] = false,		['useable'] = false,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Material - Aluminium'},
['plastic']				= {['name'] = 'plastic', 			['label'] = 'Plastic', 				['weight'] = 1,		['type'] = 'item',		['image'] = 'plastic.png', 				['unique'] = false,		['useable'] = false,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Material - Plastic'},
['rubber']				= {['name'] = 'rubber', 			['label'] = 'Rubber', 				['weight'] = 1,		['type'] = 'item',		['image'] = 'rubber.png', 				['unique'] = false,		['useable'] = false,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Material - Rubber'},
['electric_scrap']		= {['name'] = 'electric_scrap', 	['label'] = 'Electric Scrap', 		['weight'] = 1,		['type'] = 'item',		['image'] = 'electric_scrap.png', 		['unique'] = false,		['useable'] = false,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Material - Electric Scrap'},
['glass']				= {['name'] = 'glass', 				['label'] = 'Glass', 				['weight'] = 1,		['type'] = 'item',		['image'] = 'glass.png', 				['unique'] = false,		['useable'] = false,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Material - Glass'},
['copper']				= {['name'] = 'copper', 			['label'] = 'Copper', 				['weight'] = 1,		['type'] = 'item',		['image'] = 'copper.png', 				['unique'] = false,		['useable'] = false,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Material - Copper'},
['carbon_fiber']		= {['name'] = 'carbon_fiber', 		['label'] = 'Carbon Fiber', 		['weight'] = 1,		['type'] = 'item',		['image'] = 'carbon_fiber.png', 		['unique'] = false,		['useable'] = false,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Material - Carbon Fiber'},
['brass']				= {['name'] = 'brass', 				['label'] = 'Brass', 				['weight'] = 1,		['type'] = 'item',		['image'] = 'brass.png', 				['unique'] = false,		['useable'] = false,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Material - Brass'},
['synthetic_oil']		= {['name'] = 'synthetic_oil', 		['label'] = 'Synthetic Oil', 		['weight'] = 1,		['type'] = 'item',		['image'] = 'synthetic_oil.png', 		['unique'] = false,		['useable'] = false,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Material - Synthetic Oil'},
['acid']				= {['name'] = 'acid', 				['label'] = 'Synthetic Acid', 		['weight'] = 1,		['type'] = 'item',		['image'] = 'acid.png', 				['unique'] = false,		['useable'] = false,		['shouldClose'] = true,		['combinable'] = nil,	['description'] = 'Material - Synthetic Acid'},