fx_version 'cerulean'
game 'gta5'
lua54 'yes'
this_is_a_map 'yes'
name 'PlasmaBall'
version '1.0.0'
description 'Luminous ball made by patoche for PlasmaGame'
author 'Patoche'

data_file 'DLC_ITYP_REQUEST' 'stream/plasma_ball.ytyp'
dependency '/assetpacks'