RegisterNetEvent('av_meth:blip', function()
    local delivery = AddBlipForCoord(Meth.BlipCoords[1], Meth.BlipCoords[2], Meth.BlipCoords[3])
    SetBlipSprite(delivery, Meth.BlipIcon)
    SetBlipScale(delivery, Meth.BlipScale)
    SetBlipDisplay(delivery, 4)
    SetBlipColour(delivery, Meth.BlipColor)
    SetBlipAsShortRange(delivery, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentString(Lang['blip_text'])
    EndTextCommandSetBlipName(delivery)
end)